fix workflow to wait for checks (#8)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,27 @@ jobs:
           DATE=$(date +"%d%b%Y" | tr '[:upper:]' '[:lower:]')
           sed -i "s/^const cacheVersion = .*/const cacheVersion = '${DATE}';/" sw.js
 
+      - name: Wait for CodeQL checks to complete
+        run: |
+          CHECK_NAME="CodeQL"
+          CHECK_STATUS=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs | jq -r --arg CHECK_NAME "$CHECK_NAME" '.check_runs[] | select(.name == $CHECK_NAME) | .status')
+          MAX_RETRIES=10
+          RETRY_COUNT=0
+          while [ "$CHECK_STATUS" != "completed" ]; do
+            if [ -z "$CHECK_STATUS" ]; then
+              echo "Error: CHECK_STATUS is empty or invalid. Exiting."
+              exit 1
+            fi
+            if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+              echo "Error: Timeout reached. CodeQL check did not complete within the expected time."
+              exit 1
+            fi
+            echo "CodeQL check is not completed. Retrying in 30 seconds... (Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)"
+            sleep 30
+            CHECK_STATUS=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs | jq -r --arg CHECK_NAME "$CHECK_NAME" '.check_runs[] | select(.name == $CHECK_NAME) | .status')
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+          done
+
       - name: Commit and push changes
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
